[workspace]
# Update the workspace name accordingly
name = "clr_ws"
authors = ["Erik Holum <erik.holum@nasa.gov>"]
channels = [
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/robostack-jazzy",
]
# If building robostack packages locally be sure to only target the build you care about.
# For CI we are only looking at linux-64
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[activation]
# Sources the workspace install, if present
scripts = ["scripts/entrypoint_pixi.sh"]

[system-requirements]
# Needed for realsense
libc = { family = "glibc", version = "2.35" }

[activation.env]
LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LIBRARY_PATH}"
LD_LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}"
LDFLAGS = "-L${CONDA_PREFIX}/lib -Wl,-rpath,${CONDA_PREFIX}/lib -fuse-ld=mold"
COLCON_DEFAULT_OUTPUT_STYLE = "catkin_tools"
COLCON_DEFAULTS_FILE = "${PIXI_PROJECT_ROOT}/config/colcon-defaults.yaml"
RCUTILS_COLORIZED_OUTPUT = "1"

[tasks]
# Setup tasks
setup-colcon = { cmd = """
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
colcon mixin update default
""" }

# Build tasks
build = "colcon build"
test = "colcon test"
test-result = "colcon test-result --verbose"
clean = "rm -rf build/* install/* log/*"

[dependencies]
# Regular conda dependencies
python = ">=3.11,<3.13"
cmake = ">=4.1.2,<5"
ccache = ">=4.13.1,<5"
ninja = ">=1.13.1,<2"
mold = ">=2.40.4,<3"
colcon-common-extensions = ">=0.3.0,<0.4"
colcon-mixin = ">=0.2.3,<0.3"
pip = "*"
nanobind = ">=2.8.0,<3"
trimesh = ">=4.11.4,<5"
pycollada = ">=0.9.3,<0.10"
viser = ">=1.0.29,<2"
matplotlib = ">=3.10.9,<4"

# ROS dependencies
ros-jazzy-ros-base = "*"
ros-jazzy-admittance-controller = "*"
ros-jazzy-angles = "*"
ros-jazzy-behaviortree-cpp = "*"
ros-jazzy-cv-bridge = "*"
ros-jazzy-depth-image-proc = "*"
ros-jazzy-force-torque-sensor-broadcaster = "*"
ros-jazzy-forward-command-controller = "*"
ros-jazzy-gripper-controllers = "*"  # TODO: This is deprecated, use parallel-gripper-controller
ros-jazzy-image-geometry = "*"
ros-jazzy-image-transport = "*"
ros-jazzy-joint-state-broadcaster = "*"
ros-jazzy-joint-trajectory-controller = "*"
ros-jazzy-kinematics-interface-kdl = "*"
ros-jazzy-moveit-configs-utils = "*"
ros-jazzy-moveit-core = "*"
ros-jazzy-moveit-msgs = "*"
ros-jazzy-moveit-planners-chomp = "*"
ros-jazzy-moveit-planners-ompl = "*"
ros-jazzy-moveit-planners-stomp = "*"
ros-jazzy-moveit-ros-control-interface = "*"
ros-jazzy-moveit-ros-planning-interface = "*"
ros-jazzy-moveit-ros-visualization = "*"
ros-jazzy-moveit-visual-tools = "*"
ros-jazzy-mujoco-vendor = "*"
ros-jazzy-pilz-industrial-motion-planner = "*"
ros-jazzy-pinocchio = "*"
ros-jazzy-position-controllers = "*"
ros-jazzy-python-qt-binding = "*"
ros-jazzy-realsense2-description = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-control-cmake = "*"
ros-jazzy-trac-ik-kinematics-plugin = "*"
ros-jazzy-ur-controllers = "*"
ros-jazzy-ur-dashboard-msgs = "*"
ros-jazzy-ur-description = "*"
ros-jazzy-ur-msgs = "*"
ros-jazzy-ur-robot-driver = "*"
ros-jazzy-velocity-controllers = "*"
ros-jazzy-xacro = "*"

# Dependencies that not available on conda-forge and must be fetched from PyPi.
# Try not to use this section unless absolutely necessary.
[pypi-dependencies]
filelock = ">=3.29.1, <4"
mujoco = "==3.4.0"
obj2mjcf = ">=0.0.25, <0.0.26"
