waypoints:
  demo_home:
    config:
    - 3.1927
    - -2.3913
    - -1.7760
    - -0.4700
    - -1.6177
    - -1.6134
    planning_group: "ur_manipulator"
    cartesian: false
    planner: "RRTstarkConfigDefault"
  init:
    config:
    - 0.0
    - 0.0
    - 2.5656  # 147 deg
    - -3.0020 # -172 deg
    - -0.9599 # -55 deg
    - -0.6982 # -40 deg
    - -1.5184 # -87 deg
    - -1.0297 # -59 deg
    planning_group: "clr"
    cartesian: false
    planner: "RRTstarkConfigDefault"
  approach_bench_seat:
    config:
    - 2.443 # 141 deg
    - -2.670 # -153.7 deg
    - -1.571 # -88 deg
    - -0.419 # -25.7 deg
    - -1.500 # -86.5 deg
    - -0.925 # -53.8 deg
    planning_group: "ur_manipulator"
    cartesian: false
    planner: "RRTstarkConfigDefault"
  back_out:
    pose:
      x: 0.0
      y: 0.0
      z: -0.4
      qx: 0.0
      qy: 0.0
      qz: 0.0
      qw: 1.0
    planning_group: "ur_manipulator"
    cartesian: true
    relative: true
  approach_stow:
    config:
      - 0.500
    planning_group: "rail"
    cartesian: false
  stow:
    # config:
    # - 4.17133 # 238 deg
    # - -2.6529 # -152 deg
    # - 2.44346 # 140 deg
    # - 0.0
    # - 1.0821 # 62 deg
    # - 0.1222 # 7 deg
    config:
    - 1.5010 # 86 deg
    - -0.3316 # -19 deg
    - -2.2515 # -129 deg
    - -3.6477 # -209 deg
    - -1.5533 # -89 deg
    - 1.5708 # 90 deg
    planning_group: "ur_manipulator"
    cartesian: false
    planner: "RRTstarkConfigDefault"
  traverse_right:
    config:
    - 1.200
    planning_group: "rail"
    cartesian: false
  ctb_offset:
    pose:
      x: 0.0
      y: 0.0
      z: -0.05
      qx: 0.0
      qy: 0.0
      qz: 1.0
      qw: 0.0
    planning_group: "ur_manipulator"
    cartesian: true
    relative: true
  descend_to_ctb_handle:
    pose:
      x: 0.0
      y: 0.0
      z: 0.08
      qx: 0.0
      qy: 0.0
      qz: 0.0
      qw: 1.0
    planning_group: "ur_manipulator"
    cartesian: true
    relative: true
  close_grasp:
    preset_name: "close"
    planning_group: "hand"
  lift_relative:
    pose:
        x: 0.0
        y: 0.0
        z: -0.2
        qx: 0.0
        qy: 0.0
        qz: 0.0
        qw: 1.0
    planning_group: "ur_manipulator"
    cartesian: true
    relative: true
  lift_lift:
    config:
    - 0.680
    planning_group: "lift"
    cartesian: false
  stow_ctb:
    pose:
      x: 0.0
      y: 0.1
      z: 0.0
      qx: 0.0
      qy: 0.0
      qz: 0.0
      qw: 1.0
    planning_group: "ur_manipulator"
    cartesian: true
    relative: true
  traverse_left_1:
    config:
    - 0.300
    planning_group: "rail"
    cartesian: false
  pre_drop_ctb:
    pose:
      x: -1.006
      y: 0.811
      z: 1.580
      qx: 0.725
      qy: 0.688
      qz: 0.032
      qw: -0.004
    planning_group: "ur_manipulator"
    cartesian: false
  traverse_left_2:
    config:
    - 0.000
    planning_group: "rail"
    cartesian: false
  center_ctb:
    pose:
      x: 0.0
      y: -0.25
      z: 0.0
      qx: 0.0
      qy: 0.0
      qz: 0.0
      qw: 1.0
    planning_group: "ur_manipulator"
    cartesian: true
    relative: true
  drop_arm:
    pose:
      x: -0.05
      y: 0.0
      z: 0.1
      qx: 0.0
      qy: 0.0
      qz: 0.0
      qw: 1.0
    planning_group: "ur_manipulator"
    cartesian: true
    relative: true
  drop_lift:
    config:
    - 0.000
    planning_group: "lift"
    cartesian: false
  open_grasp:
    preset_name: "open"
    planning_group: "hand"
  back_off:
    pose:
      x: 0.0
      y: 0.0
      z: -0.05
      qx: 0.0
      qy: 0.0
      qz: 0.0
      qw: 1.0
    planning_group: "ur_manipulator"
    cartesian: true
    relative: true
