# This workflow requires LFS objects, and so should be run less frequently
# to reduce bandwidth requirements.
name: build_and_push_images
on:
  # Run weekly on Monday morning
  schedule:
    - cron: '0 8 * * 1'
  # Always push tagged version
  push:
    tags:
      - '*'
  # Run and push on request
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-functional
  cancel-in-progress: true

jobs:
  test_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Clone lfs objects required for full functional tests
        run: git submodule foreach --recursive 'git lfs pull'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          flavor: |
            latest=false
      # TODO: Pull these once they are available
      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          target: er4-dev-source
          push: false
          load: true
          cache-from: type=gha,scope=ros-${{ github.event.repository.name }}
      - name: Run functional tests
        run: |
          docker run --rm \
            ${{ steps.meta.outputs.tags }} \
            bash -c "
              colcon test --packages-select clr_functional_tests &&
              colcon test-result --verbose
            "
      # Only push if the tests pass
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          target: er4-dev-source
          push: true
          cache-from: type=gha,scope=ros-${{ github.event.repository.name }}
